### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by oaksagelew** [dcocchia/Ity#1]
It's "minUscule", not "minIscule"

**Comment by dcocchia** [comment]
Seems like a hotly debated [issue](http://english.stackexchange.com/questions/5350/miniscule-vs-minuscule)!

I'm ok with the mini spelling for now, since it's what came naturally to me. :smile:

**Comment by oaksagelew** [comment]
No, there’s no debate. Check the origin of the word and you will see its original spelling. Revisionist history abounds, but that doesn’t actually alter the facts. It’s a French word with a well defined origin. And even your debate link shows more comments supporting the correct spelling.

It’s you repo so you do what you want – just know that spelling errors diminish your credibility. And just because something comes naturally doesn’t make it correct.
